#+TITLE: FSharp.mk
#+AUTHOR: Bart Post

* A Makefile inclusion to build F# projects without xml

   FSharp.mk aims to replace all .sln and .fsproj files from an F#
   project.  As of the moment of this writing, those both are not
   intended for manual editing, and expect you to use some tool.

   Luckily, we still have [[https://www.gnu.org/software/make/][GNU Make]], which is free and has been around
   long enough to be able to do almost anything in the way of building
   projects.

* Why?

   Quoting [[http://fsharp.org/guides/mac-linux-cross-platform/#fsproj-and-sln-files][fsharp.org]]:

#+BEGIN_QUOTE
To create a .fsproj file from scratch yourself, either install Xamarin Studio or MonoDevelop, or find an existing one, copy it and edit it by hand.
#+END_QUOTE

   This, of course, will not do (at least, for me).  Nothing wrong
   with copying and editing, but what is the minimum viable fsproj
   file?  And do I really need to give all my projects a GUID and
   reference them in three levels of xml nesting?  (I may be
   exaggerating here.)

   Of course, [[http://fsharp.org/guides/mac-linux-cross-platform/#makefiles][fsharp.org]] also points out that the:

#+BEGIN_QUOTE
F# command-line compiler (fsharpc) can be used with Makefiles in the usual way.
#+END_QUOTE

   Which is exactly what this project intends to do.

* How to use it

** Prerequisites

    At this moment, I am developing it on a [[https://nixos.org/][NixOS]] machine, so I can
    tell you about its prerequisites.

*** [[https://www.gnu.org/software/make/][GNU Make]], of course

     May be installed from a package called =gnumake=.  On Ubuntu, it
     seems to be in =build-essential=.  But it could already be on
     your system.

*** [[http://fsharp.org/][The FSharp compiler]]

     This provides the fsharpc command, needed to compile your code.
     There's probably a package called =fsharp=, which will require
     the =mono= package as well.

** Creating a project

    As with all Make projects, you will need to provide a Makefile
    that describes the way that sources combine to your final
    assembly.  In this Makefile, you'll need to include the [[file:FSharp.mk][FSharp.mk]]
    given in this project.  [[file:Makefile.template][A template for your Makefile]] is provided.
